[package]
name = "standard"
version = "0.1.0"
authors = ["Abby <i@abby.md>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib","lib"]

[dependencies]
smart_contract = { path = "../../smart-contract" }
smart_contract_macro = { path = "../../smart-contract-macro"}